name: Mobile pr-check

trigger:
  - none

pr: 
  branches: 
    include:
    - '*'

variables:
  - group: flutter-envs #to load the envs


pool:
  vmImage: 'macOS-latest'

steps:
  - task: FlutterInstall@0
    inputs:
      mode: 'auto'
      channel: 'stable'
      version: 'custom'
      customVersion: 'your_flutter_version' #example 2.8.1

  - script: |
      echo '##vso[task.prependpath]$(FlutterToolPath)'
      echo '##vso[task.prependpath]$(FlutterToolPath)/cache/dart-sdk/bin'
    displayName: 'Put flutter and dart in path'

  - script: |
      # Any value works, this is only static checks
      flutter packages get
      dart tools/env_generator.dart
      flutter packages pub run build_runner build --delete-conflicting-outputs
    displayName: 'Install deps and gen sources for analyzer check'
    env: 
      ENV1: $(NAME_ENV)
