#To create a keystore 
# (MAC/LINUX) - keytool -genkey -v -keystore ~/upload-keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias upload
# (WINDOWS) - keytool -genkey -v -keystore c:\Users\USER_NAME\upload-keystore.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias upload

#https://docs.flutter.dev/deployment/android


trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

# Variables needed for this script
variables:
  - group: flutter-envs #to load the envs
  
#your key.properties and project_name.jks have to be in base64 and added as secure file

steps:
  - task: DownloadSecureFile@1
    name: keyProperties
    displayName: 'Download Key Properties'
    inputs:
      secureFile: 'your-key.properties'

  - task: DownloadSecureFile@2
    name: keystore
    displayName: 'Download Keystore'
    inputs:
      secureFile: 'your-key.jks'

  # We use beta for now - until web comes out.
  - task: FlutterInstall@0
    displayName: 'Flutter install'
    inputs:
      mode: 'auto'
      channel: 'stable'
      version: 'custom'
      customVersion: 'your_flutter_version' #example 2.8.1

  - script: |
      echo '##vso[task.prependpath]$(FlutterToolPath)'
      echo '##vso[task.prependpath]$(FlutterToolPath)/cache/dart-sdk/bin'
    displayName: 'Put flutter and dart in path'

  - script: |
       cd android
       echo "Decoded Keystore"
       echo $(keystore.secureFilePath)
       base64 --decode $(keystore.secureFilePath) > app/your-key.jks 
      #  Taking your keystore and decoding to the folder app
       if [ $? -ne 0 ]; then
         echo "========== KEYSTORE DECODED ERROR =========="
         exit 1
       fi

       echo "Decoded Key properties"
       echo $(keyProperties.secureFilePath)
       base64 --decode $(keyProperties.secureFilePath) > key.properties
       #  Taking your key.properties and decoding to the folder app
       if [ $? -ne 0 ]; then
         echo "========== KEY PROPERTIES DECODED ERROR =========="
         exit 1
       fi
    displayName: 'Create key files for android'
    
  - script: |
      dart tools/env_generator.dart 
    displayName: 'Generate Environments Variables'
    env:
      ENV1: $(NAME_ENV)

  - script: |
      cd android
      fastlane beta --verbose
    displayName: 'Run fastlane'