trigger:
  - none

pool:
  vmImage: 'macos-latest'

# Variables needed for this script
#* MATCH_PASSWORD: password created for access your repository git or azure
#* AZURE_TOKEN: Your token generated in personal access token azure
#* FASTLANE_USER: Your App Store Connect / Apple Developer Portal user, if your fastlane setup accesses App Store Connect or the Apple Developer Portal (e.g. submit a TestFlight build, create a profile, ...)
#* FASTLANE_PASSWORD: Your App Store Connect / Apple Developer Portal password, usually only needed if you also set the FASTLANE_USER variable
#* FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD - App specific password (generated in Apple Developer)



variables:
  - group: flutter-envs #to load the envs

steps:
  # We use beta for now - until web comes out.
  - task: FlutterInstall@0
    displayName: 'Flutter install'
    inputs:
      mode: 'auto'
      channel: 'stable'
      version: 'custom'
      customVersion: 'your_flutter_version' #example 2.8.1

  - script: |
      echo '##vso[task.prependpath]$(FlutterToolPath)'
      echo '##vso[task.prependpath]$(FlutterToolPath)/cache/dart-sdk/bin'
    displayName: 'Put flutter and dart in path'
  
  - script: |
      cd ios
      fastlane beta --verbose
    displayName: 'Run fastlane beta'
    env:
      MATCH_PASSWORD: $(MATCH_PASSWORD)
      AZURE_TOKEN: $(AZURE_TOKEN)
      FASTLANE_PASSWORD: $(FASTLANE_PASSWORD)
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: $(FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD)
      FASTLANE_USER: $(FASTLANE_USER)

