# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#


# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


#this file no cant need generate be fastlane init

default_platform(:android)

platform :android do

  desc "Runs a clean flutter build"
    lane :build_flutter do
      Dir.chdir "../.." do
        sh("flutter", "clean")
        sh("flutter", "packages", "get")
        sh("dart", "tools/env_generator.dart")
        sh("flutter", "packages", "pub", "run", "build_runner", "build", "--delete-conflicting-outputs")
        sh("flutter", "build", "appbundle")
    end
  end

  desc "Deploy a new beta build to Google Play"
  lane :beta do
    build_flutter

    upload_to_play_store(
     track: 'beta',
     aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end
end